server:
  port: 80

logging:
  level:
    com:
#      # 监控连接的情况
      lsh: debug
    org:
      hibernate:
        resource:
#          # 监控连接的情况
          jdbc: trace
        engine:
          transaction:
            internal:
#              打印事务详情
              TransactionImpl: debug
      springframework:
#              打印事务详情
        jpa: debug
#              打印事务详情
        transaction: TRACE



spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lshdemo0?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true&serverTimezone=Asia/Shanghai
#    在数据连接中加上 logger=Slf4JLogger&profileSQL=true，用来显示 MySQL 执行的 SQL 日志
#    url: jdbc:mysql://127.0.0.1:3306/lshdemo0?logger=Slf4JLogger&profileSQL=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
#    hibernate:
#      ddl-auto: update
#      #      检查是否有数据库，自动生成
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true